Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,87 +1,84 @@
 #!/bin/bash
 
 #load functions
-source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"
+source "$HOME/pi-ware-pyqt5/func/api" || echo "failed to source $HOME/pi-ware-pyqt5/func/api"
 
 #Install python packages
 echo "Installing GUI dependencies..."
 sudo apt-get install qt5-default pyqt5-dev pyqt5-dev-tools python3-pyqt5.qtwebkit-dbg
-wget https://www.riverbankcomputing.com/static/Downloads/sip/4.19.24/sip-4.19.24.tar.gz
-tar -xzvf sip-4.19.24.tar.gz
-cd sip-4.19.24
-python configure.py
-make
-sudo rm sip-4.19.24
-sudo rm sip-4.19.24.tar.gz
-sudo pip3 install pyqt5
+#wget https://www.riverbankcomputing.com/static/Downloads/sip/4.19.24/sip-4.19.24.tar.gz
+#tar -xzvf sip-4.19.24.tar.gz
+#cd sip-4.19.24
+#python configure.py
+#make
+#sudo rm sip-4.19.24
+#sudo rm sip-4.19.24.tar.gz
+#sudo pip3 install pyqt5
 
 #Main
 echo "Installing pi-ware..."
-mkdir -p $HOME/pi-ware/logs
+mkdir -p $HOME/pi-ware-pyqt5/logs
 #Make required directory for updater
-mkdir -p "$PW_PREFIX/share/pi-ware"
-echo $(git rev-parse main) > "$PW_PREFIX/share/pi-ware/version"
+mkdir -p "$PW_PREFIX/share/pi-ware-pyqt5"
+echo $(git rev-parse main) > "$PW_PREFIX/share/pi-ware-pyqt5/version"
 echo "Creating a desktop entry for Pi-Ware..."
 mkdir -p $HOME/.local/share/applications
 echo "[Desktop Entry]
 Name=Pi-Ware
 Comment=Raspberry Pi app store
-Exec=python3 $HOME/pi-ware/store/main.py
-Icon=$HOME/pi-ware/icons/logo.png
+Exec=python3 $HOME/pi-ware-pyqt5/store/main.py
+Icon=$HOME/pi-ware-pyqt5/icons/logo.png
 Categories=Utility;
 Type=Application
-Terminal=false" > $HOME/.local/share/applications/pi-ware.desktop
+Terminal=false" > $HOME/.local/share/applications/pi-ware-pyqt5.desktop
 #Copy to desktop
-cp -r $HOME/.local/share/applications/pi-ware.desktop $HOME/Desktop/pi-ware.desktop
-#Remove settings button
-#echo "Creating a settings desktop entry for Pi-Ware..."
-#echo "[Desktop Entry]
-#Name=Pi-Ware Settings
-#Comment=Change some of pi-ware's settings
-#Exec=python3 $HOME/pi-ware/func/settings/settings.py
-#Icon=$HOME/pi-ware/icons/logo.png
-#Categories=Utility;
-#Type=Application
-#Terminal=false" > $HOME/.local/share/applications/pi-ware-settings.desktop
+cp -r $HOME/.local/share/applications/pi-ware-pyqt5.desktop $HOME/Desktop/pi-ware-pyqt5.desktop
+#Settings button
+echo "Creating a settings desktop entry for Pi-Ware..."
+echo "[Desktop Entry]
+Name=Pi-Ware Settings
+Comment=Change some of pi-ware's settings
+Exec=python3 $HOME/pi-ware-pyqt5/func/settings/settings.py
+Icon=$HOME/pi-ware-pyqt5/icons/logo.png
+Categories=Utility;
+Type=Application
+Terminal=false" > $HOME/.local/share/applications/pi-ware-pyqt5-settings.desktop
 echo "Creating an auto updater for Pi-Ware..."
 mkdir -p $HOME/.config/autostart/
 echo "[Desktop Entry]
 Name=Pi-Ware-Auto-Updater
 Comment=Auto updater for pi-ware
-Exec=bash $HOME/pi-ware/func/update/auto-update
-Icon=$HOME/pi-ware/icons/logo.png
+Exec=bash $HOME/pi-ware-pyqt5/func/update/auto-update
+Icon=$HOME/pi-ware-pyqt5/icons/logo.png
 Categories=Utility;
 Type=Application
-Terminal=false" > $HOME/.config/autostart/update-pi-ware.desktop
+Terminal=false" > $HOME/.config/autostart/update-pi-ware-pyqt5.desktop
 #Create pi-ware utility
 cd $HOME
 sudo mkdir -p "/usr/local/bin"
-sudo cp -r "$HOME/pi-ware/func/term/pi-ware-term" "/usr/local/bin/pi-ware"
-sudo chmod +x /usr/local/bin/pi-ware
+sudo cp -r "$HOME/pi-ware-pyqt5/func/term/pi-ware-term" "/usr/local/bin/pi-ware-pyqt5"
+sudo chmod +x /usr/local/bin/pi-ware-pyqt5
 echo "Added pi-ware-commands to Terminal!"
 echo "Please restart terminal to apply changes."
 #Set aarch
 echo "Your aarch type is: $(uname -m)"
 if [ "$(uname -m)" == "armv7l" ]; then
-  echo "armv7l" > $HOME/.local/share/pi-ware/arch
+  echo "armv7l" > $HOME/.local/share/pi-ware-pyqt5/arch
 elif [ "$(uname -m)" == "aarch64" ]; then
-  echo "aarch64" > $HOME/.local/share/pi-ware/arch
+  echo "aarch64" > $HOME/.local/share/pi-ware-pyqt5/arch
 else
   warning "2" "Unable to detect arch type! Continuing install..."
 fi
 #Set package manager
 if [ -f /usr/bin/apt ];then
   echo "Package manager is: apt"
-  echo "apt-get -y" > "$PW_PREFIX/share/pi-ware/inst-pref"
+  echo "apt-get -y" > "$PW_PREFIX/share/pi-ware-pyqt5/inst-pref"
 elif [ -f /usr/bin/pacman ];then
   echo "Package manager is: pacman"
-  echo "pacman -S" > "$PW_PREFIX/share/pi-ware/inst-pref"
+  echo "pacman -S" > "$PW_PREFIX/share/pi-ware-pyqt5/inst-pref"
 else
   error "Failed to find any package manager."
 fi
-echo "Fixing script format..."
-sed -i -e 's/\r$//' $HOME/pi-ware/apps/MCPI_Modded/install
-sed -i -e 's/\r$//' $HOME/pi-ware/apps/MCPI_Modded/uninstall
 #Finished
 echo "Done!"
-echo "You can find Pi-Ware in Menu > Accessories > Pi-Ware."
+echo "You can find Pi-Ware in Menu > Accessories > Pi-Ware-PYQT5."
